AppBundle\Entity\Product\Product:

    type: entity
    table: product

    lifecycleCallbacks:
        prePersist: [setDateCreatedToNow]

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        active: { type: boolean }
        name: { type: string }
        link: { type: string, nullable: true }
        price: { type: decimal, scale: 2, unsigned: false}
        sex: { type: string(32), nullable: true }
        type: { type: string(32) }
        description: { type: text, nullable: true }
        ordinal: { type: integer }
        date_created: { type: datetime }

    oneToMany:
        product_images:
            targetEntity: AppBundle\Entity\Product\Image
            mappedBy: product
            orderBy: { 'ordinal': 'ASC' }
            cascade: [all]
            orphanRemoval: true
            fetch: EAGER
